// @generated by tools/generate_v6_registry.py; do not edit.
// Typed helpers plus a stable raw MTProto escape hatch.
// New Telegram methods do not require new Lavis registry entries.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum V6Method {
    AccountUpdateStatus,
    ContactsGetContacts,
    MessagesGetHistory,
    MessagesGetDialogs,
    RawInvoke,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct MethodSpec {
    pub name: &'static str,
    pub input: InputShape,
    pub result: ResultShape,
    pub required_capability: Option<&'static str>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum InputShape {
    UpdateStatusParams,
    ContactsHashParams,
    HistorySelfParams,
    DialogsInitialParams,
    RawTlParams,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ResultShape {
    UpdateStatusResult,
    ContactsSummary,
    HistorySummary,
    DialogsSummary,
    RawTlResult,
}

impl V6Method {
    pub const fn spec(self) -> MethodSpec {
        match self {
            Self::AccountUpdateStatus => MethodSpec {
                name: "account.updateStatus",
                input: InputShape::UpdateStatusParams,
                result: ResultShape::UpdateStatusResult,
                required_capability: Some("telegram.account.status"),
            },
            Self::ContactsGetContacts => MethodSpec {
                name: "contacts.getContacts",
                input: InputShape::ContactsHashParams,
                result: ResultShape::ContactsSummary,
                required_capability: None,
            },
            Self::MessagesGetHistory => MethodSpec {
                name: "messages.getHistory",
                input: InputShape::HistorySelfParams,
                result: ResultShape::HistorySummary,
                required_capability: None,
            },
            Self::MessagesGetDialogs => MethodSpec {
                name: "messages.getDialogs",
                input: InputShape::DialogsInitialParams,
                result: ResultShape::DialogsSummary,
                required_capability: None,
            },
            Self::RawInvoke => MethodSpec {
                name: "raw.invoke",
                input: InputShape::RawTlParams,
                result: ResultShape::RawTlResult,
                required_capability: Some("telegram.raw"),
            },
        }
    }
}

pub const METHOD_SPECS: [MethodSpec; 5] = [
    V6Method::AccountUpdateStatus.spec(),
    V6Method::ContactsGetContacts.spec(),
    V6Method::MessagesGetHistory.spec(),
    V6Method::MessagesGetDialogs.spec(),
    V6Method::RawInvoke.spec(),
];

pub fn lookup(name: &str) -> Option<V6Method> {
    match name {
        "account.updateStatus" => Some(V6Method::AccountUpdateStatus),
        "contacts.getContacts" => Some(V6Method::ContactsGetContacts),
        "messages.getHistory" => Some(V6Method::MessagesGetHistory),
        "messages.getDialogs" => Some(V6Method::MessagesGetDialogs),
        "raw.invoke" => Some(V6Method::RawInvoke),
        _ => None,
    }
}

pub fn adapter_dispatch_skeleton(method: V6Method) -> MethodSpec {
    method.spec()
}
