// @generated by tools/generate_v6_registry.py; do not edit.
// This is a reviewed allowlist, not a generic Telegram dispatcher.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum V6Method {
    AccountUpdateStatus,
    ContactsGetContacts,
    MessagesGetHistory,
    MessagesGetDialogs,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct MethodSpec {
    pub name: &'static str,
    pub input: InputShape,
    pub result: ResultShape,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum InputShape {
    UpdateStatusParams,
    ContactsHashParams,
    HistorySelfParams,
    DialogsInitialParams,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ResultShape {
    UpdateStatusResult,
    ContactsSummary,
    HistorySummary,
    DialogsSummary,
}

impl V6Method {
    pub const fn spec(self) -> MethodSpec {
        match self {
            Self::AccountUpdateStatus => MethodSpec {
                name: "account.updateStatus",
                input: InputShape::UpdateStatusParams,
                result: ResultShape::UpdateStatusResult,
            },
            Self::ContactsGetContacts => MethodSpec {
                name: "contacts.getContacts",
                input: InputShape::ContactsHashParams,
                result: ResultShape::ContactsSummary,
            },
            Self::MessagesGetHistory => MethodSpec {
                name: "messages.getHistory",
                input: InputShape::HistorySelfParams,
                result: ResultShape::HistorySummary,
            },
            Self::MessagesGetDialogs => MethodSpec {
                name: "messages.getDialogs",
                input: InputShape::DialogsInitialParams,
                result: ResultShape::DialogsSummary,
            },
        }
    }
}

pub const METHOD_SPECS: [MethodSpec; 4] = [
    V6Method::AccountUpdateStatus.spec(),
    V6Method::ContactsGetContacts.spec(),
    V6Method::MessagesGetHistory.spec(),
    V6Method::MessagesGetDialogs.spec(),
];

pub fn lookup(name: &str) -> Option<V6Method> {
    match name {
        "account.updateStatus" => Some(V6Method::AccountUpdateStatus),
        "contacts.getContacts" => Some(V6Method::ContactsGetContacts),
        "messages.getHistory" => Some(V6Method::MessagesGetHistory),
        "messages.getDialogs" => Some(V6Method::MessagesGetDialogs),
        _ => None,
    }
}

pub fn adapter_dispatch_skeleton(method: V6Method) -> MethodSpec {
    method.spec()
}
