#!/usr/bin/env python3
"""Generate the V6 typed-helper registry and the stable raw MTProto escape hatch."""
import argparse
import json
from pathlib import Path
import sys
import tempfile


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "tools" / "v6-methods.json"
OUTPUT = ROOT / "src" / "external_modules" / "v6_registry.rs"


METHODS = (
    (
        "account.updateStatus",
        "AccountUpdateStatus",
        "update_status_params",
        "update_status_result",
        "telegram.account.status",
    ),
    ("contacts.getContacts", "ContactsGetContacts", "contacts_hash_params", "contacts_summary", None),
    ("messages.getHistory", "MessagesGetHistory", "history_self_params", "history_summary", None),
    ("messages.getDialogs", "MessagesGetDialogs", "dialogs_initial_params", "dialogs_summary", None),
    # Stable escape hatch. New Telegram methods are serialized by the module
    # itself and do not require another Lavis registry entry.
    ("raw.invoke", "RawInvoke", "raw_tl_params", "raw_tl_result", "telegram.raw"),
)
INPUT_SHAPES = {
    "update_status_params": "UpdateStatusParams",
    "contacts_hash_params": "ContactsHashParams",
    "history_self_params": "HistorySelfParams",
    "dialogs_initial_params": "DialogsInitialParams",
    "raw_tl_params": "RawTlParams",
}
RESULT_SHAPES = {
    "update_status_result": "UpdateStatusResult",
    "contacts_summary": "ContactsSummary",
    "history_summary": "HistorySummary",
    "dialogs_summary": "DialogsSummary",
    "raw_tl_result": "RawTlResult",
}


def validate(document):
    if set(document) != {"methods"} or not isinstance(document["methods"], list):
        raise ValueError("registry JSON must contain only a methods array")
    methods = document["methods"]
    expected = [
        (name, input_kind, result_kind, capability)
        for name, _, input_kind, result_kind, capability in METHODS
    ]
    actual = []
    for method in methods:
        if not isinstance(method, dict) or set(method) != {"name", "input", "result", "capability"}:
            raise ValueError("each method must contain only name, input, result, and capability")
        if not all(isinstance(method[key], str) for key in ("name", "input", "result")):
            raise ValueError("method metadata tokens must be strings")
        if not (method["capability"] is None or isinstance(method["capability"], str)):
            raise ValueError("capability must be null or a string")
        actual.append(
            (method["name"], method["input"], method["result"], method["capability"])
        )
    if actual != expected:
        raise ValueError("registry methods or metadata tokens differ from the V6 contract")
    return methods


def render(methods):
    variants = [variant for _, variant, _, _, _ in METHODS]
    lines = [
        "// @generated by tools/generate_v6_registry.py; do not edit.",
        "// Typed helpers plus a stable raw MTProto escape hatch.",
        "// New Telegram methods do not require new Lavis registry entries.",
        "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]",
        "pub enum V6Method {",
    ]
    lines += [f"    {variant}," for variant in variants]
    lines += [
        "}",
        "",
        "#[derive(Debug, Clone, Copy, PartialEq, Eq)]",
        "pub struct MethodSpec {",
        "    pub name: &'static str,",
        "    pub input: InputShape,",
        "    pub result: ResultShape,",
        "    pub required_capability: Option<&'static str>,",
        "}",
        "",
        "#[derive(Debug, Clone, Copy, PartialEq, Eq)]",
        "pub enum InputShape {",
    ]
    lines += [f"    {variant}," for variant in INPUT_SHAPES.values()]
    lines += ["}", "", "#[derive(Debug, Clone, Copy, PartialEq, Eq)]", "pub enum ResultShape {"]
    lines += [f"    {variant}," for variant in RESULT_SHAPES.values()]
    lines += [
        "}",
        "",
        "impl V6Method {",
        "    pub const fn spec(self) -> MethodSpec {",
        "        match self {",
    ]
    for method, variant in zip(methods, variants):
        capability = method["capability"]
        lines += [
            f"            Self::{variant} => MethodSpec {{",
            f'                name: "{method["name"]}",',
            f'                input: InputShape::{INPUT_SHAPES[method["input"]]},',
            f'                result: ResultShape::{RESULT_SHAPES[method["result"]]},',
            (
                f'                required_capability: Some("{capability}"),'
                if capability is not None
                else "                required_capability: None,"
            ),
            "            },",
        ]
    lines += [
        "        }",
        "    }",
        "}",
        "",
        f"pub const METHOD_SPECS: [MethodSpec; {len(methods)}] = [",
    ]
    lines += [f"    V6Method::{variant}.spec()," for variant in variants]
    lines += [
        "];",
        "",
        "pub fn lookup(name: &str) -> Option<V6Method> {",
        "    match name {",
    ]
    lines += [
        f'        "{method["name"]}" => Some(V6Method::{variant}),' 
        for method, variant in zip(methods, variants)
    ]
    lines += [
        "        _ => None,",
        "    }",
        "}",
        "",
        "pub fn adapter_dispatch_skeleton(method: V6Method) -> MethodSpec {",
        "    method.spec()",
        "}",
        "",
    ]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    methods = validate(json.loads(INPUT.read_text(encoding="utf-8")))
    generated = render(methods)
    if args.check:
        with tempfile.TemporaryDirectory() as directory:
            candidate = Path(directory) / OUTPUT.name
            candidate.write_text(generated, encoding="utf-8")
            return 0 if OUTPUT.exists() and OUTPUT.read_bytes() == candidate.read_bytes() else 1
    OUTPUT.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
