#!/usr/bin/env python3
"""Generate the reviewed V6 method registry from its declarative allowlist."""
import argparse
import json
from pathlib import Path
import sys
import tempfile


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "tools" / "v6-methods.json"
OUTPUT = ROOT / "src" / "external_modules" / "v6_registry.rs"


REVIEWED = (
    ("account.updateStatus", "AccountUpdateStatus", "update_status_params", "update_status_result"),
    ("contacts.getContacts", "ContactsGetContacts", "contacts_hash_params", "contacts_summary"),
    ("messages.getHistory", "MessagesGetHistory", "history_self_params", "history_summary"),
    ("messages.getDialogs", "MessagesGetDialogs", "dialogs_initial_params", "dialogs_summary"),
)
INPUT_SHAPES = {
    "update_status_params": "UpdateStatusParams",
    "contacts_hash_params": "ContactsHashParams",
    "history_self_params": "HistorySelfParams",
    "dialogs_initial_params": "DialogsInitialParams",
}
RESULT_SHAPES = {
    "update_status_result": "UpdateStatusResult",
    "contacts_summary": "ContactsSummary",
    "history_summary": "HistorySummary",
    "dialogs_summary": "DialogsSummary",
}


def validate(document):
    if set(document) != {"methods"} or not isinstance(document["methods"], list):
        raise ValueError("registry JSON must contain only a methods array")
    methods = document["methods"]
    expected = [(name, input_kind, result_kind) for name, _, input_kind, result_kind in REVIEWED]
    actual = []
    for method in methods:
        if not isinstance(method, dict) or set(method) != {"name", "input", "result"}:
            raise ValueError("each method must contain only name, input, and result")
        if not all(isinstance(method[key], str) for key in method):
            raise ValueError("method metadata tokens must be strings")
        actual.append((method["name"], method["input"], method["result"]))
    if actual != expected:
        raise ValueError("registry methods or metadata tokens are not the reviewed allowlist")
    return methods


def render(methods):
    variants = [variant for _, variant, _, _ in REVIEWED]
    lines = [
        "// @generated by tools/generate_v6_registry.py; do not edit.",
        "// This is a reviewed allowlist, not a generic Telegram dispatcher.",
        "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]",
        "pub enum V6Method {",
    ]
    lines += [f"    {variant}," for variant in variants]
    lines += [
        "}",
        "",
        "#[derive(Debug, Clone, Copy, PartialEq, Eq)]",
        "pub struct MethodSpec {",
        "    pub name: &'static str,",
        "    pub input: InputShape,",
        "    pub result: ResultShape,",
        "}",
        "",
        "#[derive(Debug, Clone, Copy, PartialEq, Eq)]",
        "pub enum InputShape {",
    ]
    lines += [f"    {variant}," for variant in INPUT_SHAPES.values()]
    lines += ["}", "", "#[derive(Debug, Clone, Copy, PartialEq, Eq)]", "pub enum ResultShape {"]
    lines += [f"    {variant}," for variant in RESULT_SHAPES.values()]
    lines += [
        "}",
        "",
        "impl V6Method {",
        "    pub const fn spec(self) -> MethodSpec {",
        "        match self {",
    ]
    for method, variant in zip(methods, variants):
        lines += [
            f"            Self::{variant} => MethodSpec {{",
            f'                name: "{method["name"]}",',
            f'                input: InputShape::{INPUT_SHAPES[method["input"]]},',
            f'                result: ResultShape::{RESULT_SHAPES[method["result"]]},',
            "            },",
        ]
    lines += ["        }", "    }", "}", "", "pub const METHOD_SPECS: [MethodSpec; 4] = ["]
    lines += [f"    V6Method::{variant}.spec()," for variant in variants]
    lines += [
        "];",
        "",
        "pub fn lookup(name: &str) -> Option<V6Method> {",
        "    match name {",
    ]
    lines += [f'        "{method["name"]}" => Some(V6Method::{variant}),' for method, variant in zip(methods, variants)]
    lines += ["        _ => None,", "    }", "}", "", "pub fn adapter_dispatch_skeleton(method: V6Method) -> MethodSpec {", "    method.spec()"]
    lines += ["}", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    methods = validate(json.loads(INPUT.read_text(encoding="utf-8")))
    generated = render(methods)
    if args.check:
        with tempfile.TemporaryDirectory() as directory:
            candidate = Path(directory) / OUTPUT.name
            candidate.write_text(generated, encoding="utf-8")
            return 0 if OUTPUT.exists() and OUTPUT.read_bytes() == candidate.read_bytes() else 1
    OUTPUT.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
